ALTER TABLE "nations" ADD COLUMN "iso_code" text;
--> statement-breakpoint
-- Correct fifa_code to canonical FIFA 3-letter codes and populate iso_code (ISO 3166-1 alpha-2)
-- Keyed on nation name (stable). ENG and SCO have no ISO 3166-1 alpha-2 (subdivisions of GB).
UPDATE "nations" SET "fifa_code" = 'ALG', "iso_code" = 'DZ' WHERE "name" = 'Algeria';
UPDATE "nations" SET "fifa_code" = 'ARG', "iso_code" = 'AR' WHERE "name" = 'Argentina';
UPDATE "nations" SET "fifa_code" = 'AUS', "iso_code" = 'AU' WHERE "name" = 'Australia';
UPDATE "nations" SET "fifa_code" = 'AUT', "iso_code" = 'AT' WHERE "name" = 'Austria';
UPDATE "nations" SET "fifa_code" = 'BEL', "iso_code" = 'BE' WHERE "name" = 'Belgium';
UPDATE "nations" SET "fifa_code" = 'BIH', "iso_code" = 'BA' WHERE "name" = 'Bosnia & Herzegovina';
UPDATE "nations" SET "fifa_code" = 'BRA', "iso_code" = 'BR' WHERE "name" = 'Brazil';
UPDATE "nations" SET "fifa_code" = 'CAN', "iso_code" = 'CA' WHERE "name" = 'Canada';
UPDATE "nations" SET "fifa_code" = 'CPV', "iso_code" = 'CV' WHERE "name" = 'Cape Verde Islands';
UPDATE "nations" SET "fifa_code" = 'COL', "iso_code" = 'CO' WHERE "name" = 'Colombia';
UPDATE "nations" SET "fifa_code" = 'COD', "iso_code" = 'CD' WHERE "name" = 'Congo DR';
UPDATE "nations" SET "fifa_code" = 'CRO', "iso_code" = 'HR' WHERE "name" = 'Croatia';
UPDATE "nations" SET "fifa_code" = 'CUW', "iso_code" = 'CW' WHERE "name" = 'Curaçao';
UPDATE "nations" SET "fifa_code" = 'CZE', "iso_code" = 'CZ' WHERE "name" = 'Czech Republic';
UPDATE "nations" SET "fifa_code" = 'ECU', "iso_code" = 'EC' WHERE "name" = 'Ecuador';
UPDATE "nations" SET "fifa_code" = 'EGY', "iso_code" = 'EG' WHERE "name" = 'Egypt';
UPDATE "nations" SET "fifa_code" = 'ENG', "iso_code" = NULL WHERE "name" = 'England';
UPDATE "nations" SET "fifa_code" = 'FRA', "iso_code" = 'FR' WHERE "name" = 'France';
UPDATE "nations" SET "fifa_code" = 'GER', "iso_code" = 'DE' WHERE "name" = 'Germany';
UPDATE "nations" SET "fifa_code" = 'GHA', "iso_code" = 'GH' WHERE "name" = 'Ghana';
UPDATE "nations" SET "fifa_code" = 'HAI', "iso_code" = 'HT' WHERE "name" = 'Haiti';
UPDATE "nations" SET "fifa_code" = 'IRN', "iso_code" = 'IR' WHERE "name" = 'Iran';
UPDATE "nations" SET "fifa_code" = 'IRQ', "iso_code" = 'IQ' WHERE "name" = 'Iraq';
UPDATE "nations" SET "fifa_code" = 'CIV', "iso_code" = 'CI' WHERE "name" = 'Ivory Coast';
UPDATE "nations" SET "fifa_code" = 'JPN', "iso_code" = 'JP' WHERE "name" = 'Japan';
UPDATE "nations" SET "fifa_code" = 'JOR', "iso_code" = 'JO' WHERE "name" = 'Jordan';
UPDATE "nations" SET "fifa_code" = 'MEX', "iso_code" = 'MX' WHERE "name" = 'Mexico';
UPDATE "nations" SET "fifa_code" = 'MAR', "iso_code" = 'MA' WHERE "name" = 'Morocco';
UPDATE "nations" SET "fifa_code" = 'NED', "iso_code" = 'NL' WHERE "name" = 'Netherlands';
UPDATE "nations" SET "fifa_code" = 'NZL', "iso_code" = 'NZ' WHERE "name" = 'New Zealand';
UPDATE "nations" SET "fifa_code" = 'NOR', "iso_code" = 'NO' WHERE "name" = 'Norway';
UPDATE "nations" SET "fifa_code" = 'PAN', "iso_code" = 'PA' WHERE "name" = 'Panama';
UPDATE "nations" SET "fifa_code" = 'PAR', "iso_code" = 'PY' WHERE "name" = 'Paraguay';
UPDATE "nations" SET "fifa_code" = 'POR', "iso_code" = 'PT' WHERE "name" = 'Portugal';
UPDATE "nations" SET "fifa_code" = 'QAT', "iso_code" = 'QA' WHERE "name" = 'Qatar';
UPDATE "nations" SET "fifa_code" = 'KSA', "iso_code" = 'SA' WHERE "name" = 'Saudi Arabia';
UPDATE "nations" SET "fifa_code" = 'SCO', "iso_code" = NULL WHERE "name" = 'Scotland';
UPDATE "nations" SET "fifa_code" = 'SEN', "iso_code" = 'SN' WHERE "name" = 'Senegal';
UPDATE "nations" SET "fifa_code" = 'RSA', "iso_code" = 'ZA' WHERE "name" = 'South Africa';
UPDATE "nations" SET "fifa_code" = 'KOR', "iso_code" = 'KR' WHERE "name" = 'South Korea';
UPDATE "nations" SET "fifa_code" = 'ESP', "iso_code" = 'ES' WHERE "name" = 'Spain';
UPDATE "nations" SET "fifa_code" = 'SWE', "iso_code" = 'SE' WHERE "name" = 'Sweden';
UPDATE "nations" SET "fifa_code" = 'SUI', "iso_code" = 'CH' WHERE "name" = 'Switzerland';
UPDATE "nations" SET "fifa_code" = 'TUN', "iso_code" = 'TN' WHERE "name" = 'Tunisia';
UPDATE "nations" SET "fifa_code" = 'TUR', "iso_code" = 'TR' WHERE "name" = 'Türkiye';
UPDATE "nations" SET "fifa_code" = 'URU', "iso_code" = 'UY' WHERE "name" = 'Uruguay';
UPDATE "nations" SET "fifa_code" = 'USA', "iso_code" = 'US' WHERE "name" = 'USA';
UPDATE "nations" SET "fifa_code" = 'UZB', "iso_code" = 'UZ' WHERE "name" = 'Uzbekistan';
